spring:
  h2:
    console:
      enabled: true     #开启H2的控制台
  datasource:
    schema: classpath:schema.sql  #指定h2的建表
    data: classpath:data.sql   #指定h2的数据
    platform: h2    #指定数据库类型
  jpa:
    generate-ddl: false  #是否生成ddl语句  false  因为使用schema.sql和 data.qsl
    show-sql: true
    hibernate:
      ddl-auto: none   # 启动时不做ddl语句处理
  application:
    name: hd-provider-user  # 当前注册的名称  最好名称全部使用小写
server:
  port: 7900
logging:
  level:
    root: info
    org.hibernate:  info
    org.hibernate.type.descriptpr.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasciExtractor: trace
    com.hd: debug

#配置eureka的注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone:  http://hd:123@localhost:8761/eureka  #与eureka server中的地址保持一致
  instance:
    prefer-ip-address: true   #配置显示IP地址 注册之后，status信息上鼠标放上去显示的信息，默认为主机名称:端口，现在启动ip:端口
    #instance-id自定义注册时status显示的信息 ${spring.application.name}：应用名称
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}


